  <section class="main-text">
    <ul>
      <li>simplicity</li>
      <li>elegance</li>
      <li>natural</li>
      <li>simplicity</li>
      <li>elegance</li>
      <li>natural</li>
      <li>simplicity</li>
      <li>elegance</li>
      <li>natural</li>
      <li>simplicity</li>
      <li>elegance</li>
      <li>natural</li>
    </ul>
    <ul>
      <li>elegance</li>
      <li>natural</li>
      <li>simplicity</li>
      <li>elegance</li>
      <li>natural</li>
      <li>simplicity</li>
      <li>elegance</li>
      <li>natural</li>
      <li>simplicity</li>
      <li>elegance</li>
      <li>natural</li>
    </ul>
    <ul>
      <li>simplicity</li>
      <li>elegance</li>
      <li>natural</li>
      <li>simplicity</li>
      <li>elegance</li>
      <li>natural</li>
      <li>simplicity</li>
      <li>elegance</li>
      <li>natural</li>
      <li>simplicity</li>
      <li>elegance</li>
      <li>natural</li>
    </ul>
  </section>